// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWtNw43pZNOvVG1jw-RSczZCmCdK9RLe4',
    appId: '1:375273354267:web:84152e0fae067bb986b4be',
    messagingSenderId: '375273354267',
    projectId: 'dummy-925c9',
    authDomain: 'dummy-925c9.firebaseapp.com',
    databaseURL: 'https://dummy-925c9-default-rtdb.firebaseio.com',
    storageBucket: 'dummy-925c9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFPVdo3UTSaRvTAI1wAlTBinnJpyYV6pQ',
    appId: '1:375273354267:android:a0e357f01597e10f86b4be',
    messagingSenderId: '375273354267',
    projectId: 'dummy-925c9',
    databaseURL: 'https://dummy-925c9-default-rtdb.firebaseio.com',
    storageBucket: 'dummy-925c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASTX8rFTBUfLq5mJgEWQQdx4BtsIZTqyo',
    appId: '1:375273354267:ios:d60face9292aef8e86b4be',
    messagingSenderId: '375273354267',
    projectId: 'dummy-925c9',
    databaseURL: 'https://dummy-925c9-default-rtdb.firebaseio.com',
    storageBucket: 'dummy-925c9.appspot.com',
    iosBundleId: 'com.example.ttbFlutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASTX8rFTBUfLq5mJgEWQQdx4BtsIZTqyo',
    appId: '1:375273354267:ios:e596834d89d8d57286b4be',
    messagingSenderId: '375273354267',
    projectId: 'dummy-925c9',
    databaseURL: 'https://dummy-925c9-default-rtdb.firebaseio.com',
    storageBucket: 'dummy-925c9.appspot.com',
    iosBundleId: 'com.example.ttbFlutterFirebase.RunnerTests',
  );
}
